### ISSUE TITLE
Skill

### ISSUE THREAD

**Issue by Samsam-lee** [ChoMihyang/attendance-keeper#11]
Repositoryを見たら、pythonを使ったことがないようですが、pythonを選んだ理由がありますか？！
私も興味があるのでお聞きしたいです。

**Comment by ChoMihyang** [comment]
そうですね。Pythonは fastAPIというサーバーサイド実装の為に使ってますー！fastAPIは書き方が簡単で使いやすいと聞いたことがあって今回に使うことになりました＾＾
